### ISSUE TITLE
Tiles not shown / Mapbox returns 401

### ISSUE THREAD

**Issue by konstin** [opendata-stuttgart/feinstaub-map#13]
I can't see the map as all request to mapbox made by the website return a "401 Unauthorized".

**Comment by ricki-z** [comment]
we were over the 50k views limit on mapbox. map is switched to pure openstreetmap.

**Comment by konstin** [comment]
Thanks for fixing this so fast!

**Comment by michael-k** [comment]
OSM does not like this. :/

> Apart from very limited testing purposes, you should not use the tiles supplied by OpenStreetMap.org itself.

https://switch2osm.org/using-tiles/

**Comment by ricki-z** [comment]
This is work in progress. I'm implementing a tile-server. Until then the tile-caches {a,b,c}.tiles.madavi.de could be used.

**Comment by rashfael** [comment]
Using tiles.madavi.de now.
