### ISSUE TITLE
WiFi configuration password input length limits

### ISSUE THREAD

**Issue by pj4y** [opendata-stuttgart/feinstaub-map#22]
Unfortunately it is not possible to enter WiFi passwords with more than 32 characters in the config form provided with the latest firmware binary:

https://github.com/opendata-stuttgart/sensors-software/blob/master/esp8266-arduino/ppd42ns-wificonfig-ppd-sds-dht/ppd42ns-wificonfig-ppd-sds-dht.ino.nodemcu.bin

maxlength= "32"

`<input name="wlanpwd" id="wlanpwd" placeholder="Passwort" value="IWouldLikeToEnterALongPasswordHe" maxlength="32" type="password">`

**Comment by ricki-z** [comment]
We will change this in a future to maxlenght=64. (This is the maximum length for WPA2 passwords). Until now we had no one with a password longer than 20 chars.
And please use the sensors-software repo for firmware related questions. This is the map repo.

**Comment by pj4y** [comment]
https://github.com/opendata-stuttgart/sensors-software/issues/34
