### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by njumaen** [opendata-stuttgart/feinstaub-map#24]
What is needed to get this started?

I tried a fresh debian/jessie and node.js but got awful lot of dependecies... Gave up tonight after hours.

We'd like to host our own map centered on Bielefeld using your data.

Cheers,

Ralf.

**Comment by ricki-z** [comment]
Second easiest way: mirror the "site" with wget and change the file static/js/app.*.js.
Search for "t.exports={center: " and insert geo coords [52.016666666,8.516666666].
Search for "zoom", change zoom level.

Easiest way: https://www.madavi.de/feinstaub-map/?Bielefeld

**Comment by rashfael** [comment]
`npm install` should do it, no global dependencies required other than node.
If you just want to center, I just built this: http://opendata-stuttgart.github.io/feinstaub-map/?center=52.0147284,8.3805271

**Comment by ricki-z** [comment]
@rashfael : I've written a small code snippet, that crawls the coords for a city from wikidata. Maybe you can include this.

**Comment by Marwe** [comment]
correction for the link above ("easieast way"): https://www.madavi.de/sensor/feinstaub-map-sds/?Bielefeld

**Comment by njumaen** [comment]
correction still show Spätzle-City! ;-)

**Comment by ricki-z** [comment]
forgot "/sensor/" in path, sorry. Have changed it in my comment. Marwe sent an "old" link to my SDS011 map.
