### ISSUE TITLE
Add IE11 Support

### ISSUE THREAD

**Issue by Avsamoht** [opendata-stuttgart/feinstaub-map#26]
Hi All

Could IE11 Support be added? 

Lodash, Leaflet, D3, Vue and whatwg-fetch supports IE11 but a Promise Polyfill is missing:
```
SCRIPT5009: "Promise" ist undefiniert
Datei: vendor.f97452c07040b3f93115.js, Zeile: 14, Spalte: 24183
```

IE11 is still a common browser and is used by a lot of governments/administration officies

**Comment by ricki-z** [comment]
should work now, can you test this.

**Comment by Avsamoht** [comment]
tested it at home with ie11 on win10. works great
i will test it tomorrow at my working place on win7 (some restricted settings).

thanks a lot for the changes
