### ISSUE TITLE
put current location in URL

### ISSUE THREAD

**Issue by derhuerst** [opendata-stuttgart/feinstaub-map#34]
Right now, it is afaik impossible to link to a specific location on the map and/or a specific tile.

would also contribute the change if you prefer.

**Comment by ricki-z** [comment]
you can call the map with parameter center=<lat>,<lon> and zoom=<factor>
We use this to create the city and country maps.
Link for i.e Belgium is http://maps.luftdaten.info/?center=50.8,4&zoom=8 .

**Comment by derhuerst** [comment]
Thanks! Would be great to auto-update the URL just like Google Maps and OSM do it, because non-technical people won't bother to write such links.

**Comment by ricki-z** [comment]
If you can write the code for this , let me know ;-)

**Comment by derhuerst** [comment]
Never worked with Vue before, but i guess i will manage it. I put it on my list of things to do.

**Comment by k-nut** [comment]
There is actually a leaflet plugin that does all of this automatically: https://github.com/mlevans/leaflet-hash

**Comment by ricki-z** [comment]
The url is now updated on move/zoom. So you can link to a special map.
Please close the issue if this is okay.

**Comment by derhuerst** [comment]
It works. Note that this change breaks the previous scheme for linking to a specific location.

**Comment by ricki-z** [comment]
Wont really break this feature. The first call with center/zoom will set the center as expected.

**Comment by derhuerst** [comment]
Ok, let's see the URL will be misleading, containing two locations.

**Comment by ricki-z** [comment]
The location should now be changed to hash version only. But Internet Explorer seems to have a different understanding of url changes (history.pushState()) and doesn't fire the event. So there the url may contain 2 locations.

**Comment by dokape** [comment]
Great Feature. THANKS for implementing.
Using it since a few days in Mozilla and Chrome. Works perfekt.
