### ISSUE TITLE
SDS011 not shown on map

### ISSUE THREAD

**Issue by ricki-z** [opendata-stuttgart/feinstaub-map#4]
Code in src/feinstaub-api.js is changed, please deploy new version

**Comment by mfa** [comment]
@rashfael ^

**Comment by rashfael** [comment]
Just `npm run deploy`

**Comment by mfa** [comment]
i don't have npm

**Comment by rashfael** [comment]
Does @ricki-z not have the rights?

**Comment by ricki-z** [comment]
I've run `npm run deploy`. Too many deprecated modules. I will try to upload a manually changed version of main.js.

**Comment by rashfael** [comment]
I deployed it, since the mapbox api key is not in vcs.
