### ISSUE TITLE
Sensor Map: Call by City-Url leads to zoom #2 

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/feinstaub-map#42]
Call of sensor-Map via specific city url leads gets corrects location from places.js
but uses zoomlevel #2.

example:
passau.maps.luftdaten.info
leads to 
http://passau.maps.luftdaten.info/#2/48.6/13.2
showing whole earth. 

Stuttgart:
http://stuttgart.maps.luftdaten.info leads to:
http://stuttgart.maps.luftdaten.info/#2/48.8/9.2

Deutschland works:
http://deutschland.maps.luftdaten.info     leads to:
http://deutschland.maps.luftdaten.info/#6/51.165/10.455

Baden-Württemberg works also. 
http://baden-wuerttemberg.maps.luftdaten.info/     leads to 
http://baden-wuerttemberg.maps.luftdaten.info/#8/48.530/9.050

seems, only citys are affected.
Checked with Chrome 58 and Firefox 54 on Windows 10

**Comment by ricki-z** [comment]
I had changed the default location and zoom level to 0,0 and 2 for maps.luftdaten.info.
But the default level for cities should be 11. This is now changed. So the calls should work again.

**Comment by dokape** [comment]
works.

closed.
