### ISSUE TITLE
Influxx DB issue. 

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/feinstaub-map#43]
Seit vorhin. 
Heut Mittag gings noch
Android 7, chrome, via Unitymedia. 

![screenshot_20170628-200731](https://user-images.githubusercontent.com/22255381/27652876-97645504-5c3d-11e7-94f3-b3647ecde371.png)

**Comment by dokape** [comment]
29.6. 9:55h 
Scheint wieder zu laufen. Keine Fehler mehr.

**Comment by ricki-z** [comment]
War wohl eine Problem der Kommunikation zwischen Grafana und InfluxDB.
