### ISSUE TITLE
data in DB statt in Dateien schreiben

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/feinstaub-map#46]
Es scheint, das Schreiben als CSV-Dateien in eine Datei scheint derzeit mit der gestiegenen Anzahl von Sensoren und daraus resultierenden Datenmengen auf dem Server an die Grenze zu kommen.
Wäre es nicht sinnvoller, die Datenmengen in eine Datenbank zu schreiben und auf die dort vorhanden Sicherheits- und Backup-Mechanismen zu nutzen?
Auf Anforderung könnte auch die Ausgabe spezifischer Sensordaten als CSV-Datei immer noch erfolgen. 
Man könnte mit einer entsprechenden API auch schneller/einfacher regionale Zusammenfassungen und Analysen machen. (Select * from Data where sensor in "sensor1, sensor4, sensor 16" )
Die querys wären aufgrund der Datenstruktur wohl recht einfach. 
Inserts und Selects. Wohl keine Updates und keine joins. Da ist nix komplexes dabei.
Die Anzahl der Einträge ist zwar schnell ansteigend, aber konstant und ließe sich wohl gut voraussagen.
Abfragen könnte auf eine gespiegelte DB laufen zur Lastverteilung.

**Comment by ricki-z** [comment]
Welche Grenzen meinst du? Wir schreiben die Daten in eine Datenbank. Die CSVs werden einmal am Tag erstellt. Zum einen als Sicherung, zum anderen ist ein Zugriff auf eine Datenbank, in die jeden Tag über 1,5 Mio Datensätze gespielt werden, nicht ganz so trivial wie du das darstellst.
Selbst die Erstellung der JSON-Datei für die Karte, die ja 'nur' die Daten der Sensoren der letzten 5 Minuten enthält, dauert einige Sekunden. Das Ganze dann mal x Clients und wir bräuchten einen Cluster von einigen Servern. Einen Filter zu schreiben, der aus der JSON-Datei die Daten bestimmter Sensoren zieht, ist da deutlich schneller.
Ach ja, es gibt übrigens joins. Anderenfalls müssten wir zu allen Daten noch die Geo-Koordinaten speichern, was die Datenmenge mal knapp verdoppeln dürfte. So liegt diese Info für jede Node in einer extra Tabelle und muss nur einmal gespeichert und sehr selten aktualisiert werden.
Schau mal in  https://github.com/opendata-stuttgart/feinstaub-api , dort kannst du das Daten-Modell nachlesen.

**Comment by dokape** [comment]
Ok. Dann lag ich falsch. Ich war der Meinung, die Daten werden für jeden Sensor in nur in eigene Dateien geschrieben, also diese csv-Dateien. 
Stimmt, die Geodaten in eigener Tabelle reduziert, da brauchs dann joins. My Fault. 
Die Sicherung ist sicher nicht trivial, eine DB bietet ja aber entsprechende Werkzeuge von Haus. 
Ich sah nur, dass eben in letzter Zeit die Graphen nicht korrekt generiert wurden und tippte auf ein fehlerhaftes Vorhandensein der csv-Dateien/Datenbestandes. 

Bleibt die Frage: wie kann man die fehlerhaften Graphen (template-error?) vermeiden?
Oder kann man als "Nutzer" die Neugenierung der nötigen Daten für die Darstellung selbst anstoßen?
Oder wem kann man die fehlerhaften Graphen melden zum beheben?
