### ISSUE TITLE
"PMS" type sensors missing in https://api.luftdaten.info/static/v2/data.dust.min.json

### ISSUE THREAD

**Issue by Adorfer** [opendata-stuttgart/feinstaub-map#50]
Perhaps i am missing a point, but for the moment, just SDS are visible in 
https://api.luftdaten.info/static/v2/data.dust.min.json

consequence: PMS sensordate are not shown on the map.

**Comment by Adorfer** [comment]
Perhaps this is all, what is needed, probably not: 
https://github.com/opendata-stuttgart/feinstaub-map/pull/51

**Comment by ricki-z** [comment]
The data.dust.min.json should now contain the PMS sensors. But only those that have sent in the last 5 minutes.

**Comment by ricki-z** [comment]
The missing PMS7003 was caused by a missing value type (P0) at the feinstaub-api.
