### ISSUE TITLE
indicate the number of threshold violations per year for each sensor

### ISSUE THREAD

**Issue by nschloe** [opendata-stuttgart/feinstaub-map#56]
In the EU, PM10 particles can legally take a concentration of more than 50µg/m^3 on average per day at most 35 day per year. It'd be great if the details popup could show just how many times this threshold was violated in the last 365 days.

**Comment by ricki-z** [comment]
Measured by our sensor or the next 'official' station?
Our sensor can't be used to get threshold violations. It's not calibrated.
What would you say if the police would use uncalibrated hardware to measure your speed?
And the values of 'official' stations have a delay of up to 6 weeks (gravimetric measurement).

**Comment by nschloe** [comment]
> Our sensor can't be used to get threshold violations. It's not calibrated.

Are the figures coming out of the DIY-stations at least somewhere in the range of the official measurements? If yes, it'd still make sense to show the number of violations as a rough indicator. (Obviously there are no legal bindings with homemade devices.)

**Comment by ricki-z** [comment]
@nschloe Auf deutsch, weil das auf Englisch jetzt kompliziert wird:
Wir hatten schon Leute, die uns auf Grund einer Nachkommastelle bei den Durchschnittwerten für die PM-Werte vorgeworfen haben, wir würden eine Genauigkeit angeben, die der Sensor gar nicht erreichen kann. Das bei zwei Werten 2 und 3 der Mittelwert ganz einfach 2,5 ist, war dabei völlig irrelevant.
Wenn wir nun anfangen, in Grafiken die Grenzwerte zu markieren, werden wir Kommentare in die gleiche Richtung bekommen. Diesen Leuten ist es egal, daß es sich um ein homemade device handelt. Wer Grnezwerte angibt, gibt damit an, daß die Werte absolut mit diesen vergleichbar sind.

**Comment by nschloe** [comment]
> Wer Grnezwerte angibt, gibt damit an, daß die Werte absolut mit diesen vergleichbar sind.

Das stimmt wohl. Danke für die Erklärung.

**Comment by nschloe** [comment]
Aus Interesse: Wie stark korrelieren denn die Messwerte mit den behördlichen Messungen? (Link oder so reicht.)

**Comment by nschloe** [comment]
Btw:
![w](https://user-images.githubusercontent.com/181628/36796565-1b3635ea-1ca6-11e8-8b4b-b632f4fa0a8d.png)

**Comment by ricki-z** [comment]
Da muss man schon sehr gut Farben sehen, um da aus der Färbung eines Hexagons immer den richtigen Wert ablesen zu können ;-)
Wir suchen gerade Messstationen und Sensoren raus, die räumlich nahe beieinander liegen. In Zürich hatten wir Sensoren direkt an Messstationen, in Bulgarien haben wir jetzt gerade 2 Sensoren an jeweils einer Messstation. Mit diesen Daten wird das dann durchgerechnet.
Für die Züricher Sensoren hätte ich Grafana-Grafiken, die müsste ich dir aber als Screenshot 
per PM schicken. Die Mitarbeiter dort wollen die Ergebnisse dieses Vergleichs, wenn überhaupt, selbst veröffentlichen.
