### ISSUE TITLE
API liefert falsche Daten

### ISSUE THREAD

**Issue by StefanKandlbinder** [opendata-stuttgart/feinstaub-map#57]
Hallo, seit einigen Stunden liefert dieser Aufruf https://api.luftdaten.info/v1/filter/type=SDS011&area=48.323368,14.298756,50 nicht mehr die gewünschten Daten. 
Es sieht so aus als ob alle Daten ausgespuckt werden.
Was mache ich falsch?
Kann ich mir Hilfe erwarten?
Tolles Projekt, vielen Dank.

Liebe Grüße 
Stefan

**Comment by ricki-z** [comment]
Sorry, ich hatte da beim Korrigieren eines Fehlers einen neuen eingebaut. Jetzt sollte es wieder funktionieren.

**Comment by StefanKandlbinder** [comment]
Das ging ja fix - alles wieder bestens!
