### ISSUE TITLE
Make it possible to save a default view for the map

### ISSUE THREAD

**Issue by berlund** [opendata-stuttgart/feinstaub-map#65]
As a user I like to start at the same point and zoom factor in the map each time I visit fsinstaub map. This will make it more convenient using it instead of moving/zooming to my home place.

**Comment by pathmapper** [comment]
You may just bookmark the URL of the map with the hash, e.g. like this for Hamburg:

http://deutschland.maps.luftdaten.info/#13/53.5623/10.0353

13 = zoom level
53.5623 = Latitude
10.0353 = Longitude

**Comment by berlund** [comment]
Ok, thank you.
