### ISSUE TITLE
Toggle for Betterplace donation overlay

### ISSUE THREAD

**Issue by steampixel** [opendata-stuttgart/feinstaub-map#73]
Hey,

the betterplace donation overlay is a great idea. But I think it would be cool to have an option to hide this overlay if someone embeds the map. At our store window we have a tiny luftdaten.info screen that rotates over several map positions in germany and our city. (https://github.com/steampixel/luftdaten-infoscreen) This is very usefull and informative for pedestrians. Unfortunality the betterplace button is very big on our little screen and just a little useless :-)

It would be great if we could have some configuration option via URL. Something like `http://deutschland.maps.luftdaten.info/?nooverlay#7/51.944/10.327` or `http://deutschland.maps.luftdaten.info/#7/51.944/10.327/nooverlay`

I think this could be done in pure JavaScript. What do you think about this?

**Comment by ricki-z** [comment]
Hi @steampixel ,
I have published a new version that should work with the second url of your two examples.
So you have to define zoom and location and then append "/nooverlay". Then the add shouldn't be shown.

**Comment by steampixel** [comment]
Awesome! Seems to work perfectly. I will try it out later on our little screen.

**Comment by steampixel** [comment]
Hm. There seems to be some kind of an issue with that. Try the following:

Just copy the following urls into your web browser one after another and hit enter (testet on Firefox and Chrome)

```
http://deutschland.maps.luftdaten.info/#13/49.7956/9.9636/nooverlay
http://deutschland.maps.luftdaten.info/#11/49.8014/10.0337/nooverlay
https://deutschland.maps.luftdaten.info/#9/49.5760/10.9591/nooverlay
https://deutschland.maps.luftdaten.info/#8/48.865/11.841/nooverlay
https://deutschland.maps.luftdaten.info/#5/50.732/10.745/nooverlay
```
The expected behavior should be, that the map should change its area and zoom. But with the /nooverlay option this works not consistently. Our infoscreen works by replacing the src attribute of an iframe to achive this.

**Comment by ricki-z** [comment]
I have changed the map again. It seems that we can't use the url hash for this. So the 'new' format for the 5 urls is:
https://deutschland.maps.luftdaten.info/?nooverlay#13/49.7956/9.9636
https://deutschland.maps.luftdaten.info/?nooverlay#11/49.8014/10.0337
https://deutschland.maps.luftdaten.info/?nooverlay#9/49.5760/10.9591
https://deutschland.maps.luftdaten.info/?nooverlay#8/48.865/11.841
https://deutschland.maps.luftdaten.info/?nooverlay#5/50.732/10.745
(important: '?nooverlay' has to come before the zoom and position hash)

**Comment by steampixel** [comment]
Ok. Seems to work now :-) Thank you!

**Comment by ricki-z** [comment]
I have added a short description to the readme.
If everything is working as expected please close the issue.
