### ISSUE TITLE
Repository Licenses

### ISSUE THREAD

**Issue by steampixel** [opendata-stuttgart/feinstaub-map#74]
Hi,

sorry for opening this little off topic in here. I was searching for the luftdaten.info website repository. But I was only able to find the achieved version here: https://github.com/opendata-stuttgart/luftdaten.info I have a question concerning the luftdaten.info logo on the website.

It seem that no repository has some kind of valid license informations. So I dont know if its ok to use the logo in my own project. I have created a [luftdaten.info display](https://github.com/steampixel/luftdaten-infoscreen) on GitHub under an MIT license. I want to use your logo within the software. But I dont know if I can use this legal: https://github.com/steampixel/luftdaten-infoscreen/blob/master/var/www/html/luftdaten.info/luftdaten-feinstaub-selber-messen-logo.png

Can you please help me answere this question?

**Comment by ricki-z** [comment]
You can find the license for the icon in the impresum at luftdaten.info [(https://luftdaten.info/impressum/)](https://luftdaten.info/impressum/) .
The license for the icon is "created by Adam Whitcroft and is licensed as Creative Commons – Attribution (CC BY 3.0)."

**Comment by steampixel** [comment]
Perfect!
