### ISSUE TITLE
Wie lange dauert es, bis mein Sensor auf der Karte erscheint?

### ISSUE THREAD

**Issue by ituri** [opendata-stuttgart/feinstaub-map#75]
Ich habe vor 3 Wochen die Daten meines Sensors auf luftdaten.info eingetragen. Bisher erscheint er dort noch nicht. Mir ist klar, dass ihr ein großes Backlog an einzutragenden Sensoren habt, aber ich würde dennoch gerne wissen, wie ich weiter verfahren soll. 
Sollte ich das Formular nochmal abschicken? Was ist derzeit die aktuelle Bearbeitungsdauer?

Gerne würde ich in meiner Nähe Workshops zum Bau eines Feinstaubsensors anbieten, doch stelle ich es mir auch hier frustrierend vor, wenn die Teilnehmer Wochen oder gar Monate warten müssen, bis ihr Sensor auf der offiziellen Karte erscheint.

Nur um das klarzustellen: Mir ist klar, dass luftdaten.info ein ehrenamtlich getragenes Open Source-Projekt ist und ich will hier keine Forderungen aufstellen. Ich wüsste nur gerne, wie ich in diesem Fall verfahren soll.

**Comment by ricki-z** [comment]
Seit etwas über einer Woche ist nun unser Portal https://meine.luftdaten.info/ live, auf dem Sensoren durch die Nutzer selbst registriert werden können. Soweit scheint alles zu funktionieren. Daher ist es ab sofort der empfohlene Weg Sensoren anzumelden.

**Comment by ituri** [comment]
Wunderbar. Wie schon an anderer Stelle hier auf github gesagt: Vielen Dank für die tolle ehrenamtliche Arbeit!
